name: codacy-coverage-reporter
env:
  APP_DEBUG: ${{ secrets.ENV_APP_DEBUG }}
  APP_DEBUG_FILE: ${{ secrets.ENV_APP_DEBUG_FILE }}
  DISCORD_BOT_TOKEN: ${{ secrets.ENV_DISCORD_BOT_TOKEN }}
  DISCORD_SERVER_ID: ${{ secrets.ENV_DISCORD_SERVER_ID }}
  DEFAULT_LOCALE: ${{ secrets.ENV_DEFAULT_LOCALE }}
  DISCORD_BOT_CHANNELS_CATEGORY_NEW_MEMBERS: ${{ secrets.ENV_DISCORD_BOT_CHANNELS_CATEGORY_NEW_MEMBERS }}
  DISCORD_BOT_CHANNELS_CATEGORY_AWAITING_MEMBERS: ${{ secrets.ENV_DISCORD_BOT_CHANNELS_CATEGORY_AWAITING_MEMBERS }}

on:
  push:
    branches: [main, develop]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm install
      - name: Running tests
        run: npm run test:coverage
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info
