name: codacy-coverage-reporter

on:
  push:
    branches: [main, develop]

jobs:
  codacy-coverage-reporter:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    name: codacy-coverage-reporter
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing dependencies
        run: npm install --loglevel verbose
      - name: Running tests
        run: |
          npm run coverage
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./coverage/lcov.info
